query($owner: String!, $name: String!, $first: Int!) {
  repository(owner: $owner, name: $name) {
    mergeQueue {
      url
      configuration { mergeMethod maximumEntriesToBuild minimumEntriesToMerge mergingStrategy }
      entries(first: $first) {
        totalCount
        nodes {
          position
          state
          enqueuedAt
          estimatedTimeToMerge
          solo
          jump
          headCommit { oid statusCheckRollup { state } }
          pullRequest { number title url author { login } }
        }
      }
    }
  }
}
